### ISSUE TITLE
First time scroll offset not correct.

### ISSUE THREAD

**Issue by nitingohel** [gelemias/RDGliderViewController#11]
Hi,

First thanks to making such a useful sample code or Glider. I used that objective-c source and i also test Swift one but unfortunately my working project are objC.

So issue is when i set bottomToTop with following code:

```
self.bottomToTopGlideVC = [[RDGliderViewController alloc] initOn:self
                                                      WithContent:[ContentViewController new]
                                                             type:RDScrollViewOrientationBottomToTop
                                                       AndOffsets:@[@(0.2),
                                                                    @(0.5)]];

self.bottomToTopGlideVC.delegate = self;
self.bottomToTopGlideVC.marginOffset = 30;

```
I used to default show approx 30px view show and then user can drag it to expand. but issue is that first time not show correctly. check following gif that you can see the issue.

![glider](https://user-images.githubusercontent.com/5137595/33131041-580c8d6c-cfbb-11e7-89f6-66598775fc61.gif)

As you can see while app open that offset is 0, 113. after if i just lil scroll that change to 133. i have checked in side but not able to find out where the -20 change of scrollview contentOfSet.

That same things happend with swift source code as well. can you please help asap.

**Comment by gelemias** [comment]
Hi, Thank you.

So the problem is that default margin is set to 20px so when changing the margin, recalculates the contentSize and changes the offset but it happens in the same runloop - I will fix it now for both languages, thanks for noticing 👍  

#13  It will be fixed on 0.1.69 the the merge request will be concluded.

**Comment by nitingohel** [comment]
Thank you very much for quick fix and really thanks for wonderful sample code: 👍

**Comment by gelemias** [comment]
RDGliderViewController (0.1.69) successfully published
You should be able to get the fix with a "$ pod update"
Please let me know if you can still reproduce it. Cheers.

**Comment by nitingohel** [comment]
i use class not pod coz need to do some modification and thanks i am really appreciate your help. will let you know if any help requred

**Comment by nitingohel** [comment]
HI i need one help.

Can you tel me how to set fixed offset ? i mean when view open i want to set fixed default bottom to top opend fixed offset based on my toolbar. is that possible?

**Comment by gelemias** [comment]
Hi, If you need to set a fixed height you can do a simple math:

```
let content: RDGliderContentViewController = RDGliderContentViewController.init(length: 200.0)
content.view.backgroundColor = UIColor.purple
content.showShadow = true
content.cornerRadius = 10.0

let fixedHeight = 80.0
let fixedOffset = NSNumber.init(value: fixedHeight / Double(content.view.frame.height))

self.bottomToTopGlideVC = RDGliderViewController.init(parent: self,
                                                 WithContent: content,
                                                 AndType: .RDScrollViewOrientationBottomToTop,
                                                 WithOffsets: [0, fixedOffset, 1])
```
